### ISSUE TITLE
getting error in nwidart/laravel-modules - Class "Illuminate\Foundation\Console\ShowModelCommand" not found

### ISSUE THREAD

**Issue by ramonov** [queents/vilt#10]
I am getting error 
Class "Illuminate\Foundation\Console\ShowModelCommand" not found while installing ( composer required queents/vilt ) the package in laravel 10. any solution for this?

please check the installation log below:
`composer require queents/vilt
./composer.json has been updated
Running composer update queents/vilt
Loading composer repositories with package information
Updating dependencies
Lock file operations: 27 installs, 0 updates, 0 removals
  - Locking bacon/bacon-qr-code (2.0.8)
  - Locking dasprid/enum (1.0.4)
  - Locking intervention/image (2.7.2)
  - Locking jaybizzle/crawler-detect (v1.2.114)
  - Locking jenssegers/agent (v2.6.4)
  - Locking joshbrw/laravel-module-installer (v2.0.1)
  - Locking laravel/fortify (v1.17.1)
  - Locking laravel/jetstream (v2.16.2)
  - Locking league/glide (2.2.4)
  - Locking maennchen/zipstream-php (3.0.2)
  - Locking mobiledetect/mobiledetectlib (2.8.41)
  - Locking nwidart/laravel-modules (v9.0.6)
  - Locking paragonie/constant_time_encoding (v2.6.3)
  - Locking pragmarx/google2fa (v8.0.1)
  - Locking queents/api-module (v1.0.0)
  - Locking queents/base-module (v1.0.15)
  - Locking queents/generator-module (v1.0.3)
  - Locking queents/menu-module (v1.0.1)
  - Locking queents/roles-module (v1.0.1)
  - Locking queents/vilt (v1.0.6)
  - Locking spatie/image (2.2.6)
  - Locking spatie/image-optimizer (1.6.4)
  - Locking spatie/laravel-medialibrary (10.9.2)
  - Locking spatie/laravel-package-tools (1.15.0)
  - Locking spatie/laravel-permission (5.10.1)
  - Locking spatie/laravel-translatable (6.5.1)
  - Locking spatie/temporary-directory (2.1.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 27 installs, 0 updates, 0 removals
  - Downloading joshbrw/laravel-module-installer (v2.0.1)
  - Downloading dasprid/enum (1.0.4)
  - Downloading bacon/bacon-qr-code (2.0.8)
  - Downloading jaybizzle/crawler-detect (v1.2.114)
  - Downloading paragonie/constant_time_encoding (v2.6.3)
  - Downloading pragmarx/google2fa (v8.0.1)
  - Downloading laravel/fortify (v1.17.1)
  - Downloading mobiledetect/mobiledetectlib (2.8.41)
  - Downloading jenssegers/agent (v2.6.4)
  - Downloading laravel/jetstream (v2.16.2)
  - Downloading intervention/image (2.7.2)
  - Downloading league/glide (2.2.4)
  - Downloading spatie/laravel-package-tools (1.15.0)
  - Downloading spatie/laravel-translatable (6.5.1)
  - Downloading spatie/laravel-permission (5.10.1)
  - Downloading queents/vilt (v1.0.6)
  - Downloading nwidart/laravel-modules (v9.0.6)
  - Downloading queents/roles-module (v1.0.1)
  - Downloading queents/menu-module (v1.0.1)
  - Downloading queents/generator-module (v1.0.3)
  - Downloading spatie/temporary-directory (2.1.2)
  - Downloading spatie/image-optimizer (1.6.4)
  - Downloading spatie/image (2.2.6)
  - Downloading maennchen/zipstream-php (3.0.2)
  - Downloading spatie/laravel-medialibrary (10.9.2)
  - Downloading queents/base-module (v1.0.15)
  - Downloading queents/api-module (v1.0.0)
  - Installing joshbrw/laravel-module-installer (v2.0.1): Extracting archive
  - Installing dasprid/enum (1.0.4): Extracting archive
  - Installing bacon/bacon-qr-code (2.0.8): Extracting archive
  - Installing jaybizzle/crawler-detect (v1.2.114): Extracting archive
  - Installing paragonie/constant_time_encoding (v2.6.3): Extracting archive
  - Installing pragmarx/google2fa (v8.0.1): Extracting archive
  - Installing laravel/fortify (v1.17.1): Extracting archive
  - Installing mobiledetect/mobiledetectlib (2.8.41): Extracting archive
  - Installing jenssegers/agent (v2.6.4): Extracting archive
  - Installing laravel/jetstream (v2.16.2): Extracting archive
  - Installing intervention/image (2.7.2): Extracting archive
  - Installing league/glide (2.2.4): Extracting archive
  - Installing spatie/laravel-package-tools (1.15.0): Extracting archive
  - Installing spatie/laravel-translatable (6.5.1): Extracting archive
  - Installing spatie/laravel-permission (5.10.1): Extracting archive
  - Installing queents/vilt (v1.0.6): Extracting archive
  - Installing nwidart/laravel-modules (v9.0.6): Extracting archive
  - Installing queents/roles-module (v1.0.1): Extracting archive
  - Installing queents/menu-module (v1.0.1): Extracting archive
  - Installing queents/generator-module (v1.0.3): Extracting archive
  - Installing spatie/temporary-directory (2.1.2): Extracting archive
  - Installing spatie/image-optimizer (1.6.4): Extracting archive
  - Installing spatie/image (2.2.6): Extracting archive
  - Installing maennchen/zipstream-php (3.0.2): Extracting archive
  - Installing spatie/laravel-medialibrary (10.9.2): Extracting archive
  - Installing queents/base-module (v1.0.15): Extracting archive
  - Installing queents/api-module (v1.0.0): Extracting archive
6 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
Class Modules\Api\Repositories_old\OrderRepository located in ./Modules/Api/Repositories/OrderRepository.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Illuminate\Foundation\Console\ShowModelCommand" not found

  at vendor/nwidart/laravel-modules/src/Commands/ModelShowCommand.php:7
      3▕ namespace Nwidart\Modules\Commands;
      4▕ 
      5▕ use Illuminate\Foundation\Console\ShowModelCommand;
      6▕ 
  ➜   7▕ class ModelShowCommand extends ShowModelCommand
      8▕ {
      9▕ 
     10▕ 
     11▕     /**

      +2 vendor frames 

  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Nwidart\Modules\Commands\ModelShowCommand")
      +7 vendor frames 

  11  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by wtfz** [comment]
Package `nwidart/laravel-modules:^9.0` not compatible with Laravel 10. Use `composer create-project laravel/laravel vilt "9.*"` (Composer v2) to stick with Laravel 9 during installation. You can't use it with Laravel 10 unless they bump that package version to ^10.*.
