### ISSUE TITLE
npm run dev does not work

### ISSUE THREAD

**Issue by rabol** [queents/vilt#2]
I have done a simple installtion:

on a Mac, with Valet

```
laravel new vilt
```
then follow the doc on the installation 

then when I run npm run dev:

```
✘ [ERROR] [plugin vite:dep-scan] ENOENT: no such file or directory, open '/Users/rabol/code/web/vilt/Modules/undefined/Resources/views/app.js'

```

**Comment by 3x1io** [comment]
i think you are forget to add THEME_MODULE=UI to `.env` file try it
